2025-09-28 01:40:41,475 INFO: Iniciando Sistema de Facturaci�n [in C:\Users\guido\OneDrive\Documentos\tp2\sis_facturacion\app\__init__.py:44]
2025-09-28 01:40:41,981 INFO: Iniciando Sistema de Facturaci�n [in C:\Users\guido\OneDrive\Documentos\tp2\sis_facturacion\app\__init__.py:44]
2025-09-28 01:40:44,147 WARNING: P�gina no encontrada: http://127.0.0.1:5000/static/favicon.ico [in C:\Users\guido\OneDrive\Documentos\tp2\sis_facturacion\app\__init__.py:143]
2025-09-28 01:42:15,518 INFO: Iniciando Sistema de Facturaci�n [in C:\Users\guido\OneDrive\Documentos\tp2\sis_facturacion\app\__init__.py:44]
2025-09-28 01:42:57,014 INFO: Iniciando Sistema de Facturaci�n [in C:\Users\guido\OneDrive\Documentos\tp2\sis_facturacion\app\__init__.py:44]
2025-09-28 01:42:57,542 INFO: Iniciando Sistema de Facturaci�n [in C:\Users\guido\OneDrive\Documentos\tp2\sis_facturacion\app\__init__.py:44]
2025-09-28 01:43:20,521 INFO: ==== INTENTO DE INICIO DE SESI�N ==== [in C:\Users\guido\OneDrive\Documentos\tp2\sis_facturacion\app\auth.py:23]
2025-09-28 01:43:20,737 INFO: Contrase�a v�lida - Iniciando sesi�n... [in C:\Users\guido\OneDrive\Documentos\tp2\sis_facturacion\app\auth.py:39]
2025-09-28 01:43:20,737 INFO: Usuario autenticado con �xito [in C:\Users\guido\OneDrive\Documentos\tp2\sis_facturacion\app\auth.py:44]
2025-09-28 01:43:30,055 INFO: [POST] Solicitud de eliminaci�n de producto ID=2 [in C:\Users\guido\OneDrive\Documentos\tp2\sis_facturacion\app\routes.py:151]
2025-09-28 01:43:30,073 INFO: Producto ID=2 eliminado correctamente [in C:\Users\guido\OneDrive\Documentos\tp2\sis_facturacion\app\routes.py:157]
2025-09-28 01:44:42,451 INFO: Procesando item 0: producto_id=3, cantidad=20, precio=150.00 [in C:\Users\guido\OneDrive\Documentos\tp2\sis_facturacion\app\routes.py:195]
2025-09-28 01:44:42,451 INFO: Procesando item 1: producto_id=4, cantidad=50, precio=30.00 [in C:\Users\guido\OneDrive\Documentos\tp2\sis_facturacion\app\routes.py:195]
2025-09-28 01:44:57,102 INFO: [POST] Solicitud de eliminaci�n de producto ID=3 [in C:\Users\guido\OneDrive\Documentos\tp2\sis_facturacion\app\routes.py:151]
2025-09-28 01:44:57,113 INFO: Producto ID=3 eliminado correctamente [in C:\Users\guido\OneDrive\Documentos\tp2\sis_facturacion\app\routes.py:157]
2025-09-28 01:45:10,074 INFO: Cierre de sesi�n para el usuario: admin@example.com [in C:\Users\guido\OneDrive\Documentos\tp2\sis_facturacion\app\auth.py:92]
2025-09-28 01:55:06,931 INFO: Iniciando Sistema de Facturaci�n [in C:\Users\guido\OneDrive\Documentos\tp2\sis_facturacion\app\__init__.py:44]
2025-09-28 01:55:07,444 INFO: Iniciando Sistema de Facturaci�n [in C:\Users\guido\OneDrive\Documentos\tp2\sis_facturacion\app\__init__.py:44]
2025-09-28 01:55:17,798 INFO: ==== INTENTO DE INICIO DE SESI�N ==== [in C:\Users\guido\OneDrive\Documentos\tp2\sis_facturacion\app\auth.py:23]
2025-09-28 01:55:18,008 INFO: Contrase�a v�lida - Iniciando sesi�n... [in C:\Users\guido\OneDrive\Documentos\tp2\sis_facturacion\app\auth.py:39]
2025-09-28 01:55:18,008 INFO: Usuario autenticado con �xito [in C:\Users\guido\OneDrive\Documentos\tp2\sis_facturacion\app\auth.py:44]
2025-09-28 01:55:29,982 INFO: Accediendo a la ruta de reportes [in C:\Users\guido\OneDrive\Documentos\tp2\sis_facturacion\app\routes.py:284]
2025-09-28 01:55:43,927 INFO: Accediendo a la ruta de reportes [in C:\Users\guido\OneDrive\Documentos\tp2\sis_facturacion\app\routes.py:284]
2025-09-28 01:55:43,932 INFO: Generando reporte con datos: {'fecha_desde': datetime.date(2025, 9, 28), 'fecha_hasta': datetime.date(2025, 9, 28), 'cliente_id': 0, 'submit': True, 'csrf_token': 'ImRiYWQ5MjE0ODFkZTAwYjVjMjk5MWExNjI3MjZmOGU0ODdhZTE5NmMi.aNi_wQ.h3jwcyaXktj6eZpViqciT9N5G24'} [in C:\Users\guido\OneDrive\Documentos\tp2\sis_facturacion\app\routes.py:302]
2025-09-28 01:55:43,935 INFO: Reporte generado exitosamente [in C:\Users\guido\OneDrive\Documentos\tp2\sis_facturacion\app\routes.py:354]
2025-09-28 01:56:17,674 INFO: Cierre de sesi�n para el usuario: admin@example.com [in C:\Users\guido\OneDrive\Documentos\tp2\sis_facturacion\app\auth.py:92]
